# server
server:
  port: 8080
  tomcat:
    connection-timeout: 10s
    accept-count: 100

# spring
spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.mybatis.spring.boot.autoconfigure.MybatisAutoConfiguration
  resources:
    add-mappings: false
  task:
    execution:
      pool:
        core-size: 50
        max-threads: 50
        queue-capacity: 10
        keep-alive: 10s

# datasource
datasource:
  userdb:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: @{datasource.userdb.url}
    username: @{datasource.userdb.username}
    password: @{datasource.userdb.password}
    maximum-pool-size: @{datasource.userdb.maximumPoolSize}
    connection-timeout: 3000
    max-lifetime: 600000